-- Add up migration script here
CREATE TABLE IF NOT EXISTS roles(
    role_id SMALLINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    role_name VARCHAR(255)
);

CREATE TABLE "users" (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    photo VARCHAR NOT NULL DEFAULT 'default.png',
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    password VARCHAR(100) NOT NULL,
    role SMALLINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    FOREIGN KEY(role) REFERENCES roles(role_id)
);

CREATE INDEX users_email_idx ON users (email);